import './globals.css'
import { Libre_Baskerville } from 'next/font/google'


const libreBaskerville = Libre_Baskerville({ subsets: ['latin'], weight: '400' })

export const metadata = {
  title: 'Pizza Stop',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <body className={libreBaskerville.className}>{children}</body>
    </html>
  )
}
